--------------------------------------------------------
-- Archivo creado  - domingo-agosto-12-2018   
--------------------------------------------------------
  DROP TABLE "VENDEDOR"."TBL_CATEGORIA" cascade constraints;
  DROP TABLE "VENDEDOR"."TBL_CLIENTE" cascade constraints;
  DROP TABLE "VENDEDOR"."TBL_ESTADO" cascade constraints;
  DROP TABLE "VENDEDOR"."TBL_INGREDIENTE" cascade constraints;
  DROP TABLE "VENDEDOR"."TBL_INGREDIENTE_PRODUCTO" cascade constraints;
  DROP TABLE "VENDEDOR"."TBL_PEDIDO" cascade constraints;
  DROP TABLE "VENDEDOR"."TBL_PEDIDO_USUARIO" cascade constraints;
  DROP TABLE "VENDEDOR"."TBL_PERMISO" cascade constraints;
  DROP TABLE "VENDEDOR"."TBL_PERMISO_USUARIO" cascade constraints;
  DROP TABLE "VENDEDOR"."TBL_PRODUCTO" cascade constraints;
  DROP TABLE "VENDEDOR"."TBL_PRODUCTO_TIENDA" cascade constraints;
  DROP TABLE "VENDEDOR"."TBL_ROL" cascade constraints;
  DROP TABLE "VENDEDOR"."TBL_TERMINAL" cascade constraints;
  DROP TABLE "VENDEDOR"."TBL_TIENDA" cascade constraints;
  DROP TABLE "VENDEDOR"."TBL_USUARIO" cascade constraints;
  DROP SEQUENCE "VENDEDOR"."TBL_CATEGORIA_SEQ";
  DROP SEQUENCE "VENDEDOR"."TBL_CLIENTE_SEQ";
  DROP SEQUENCE "VENDEDOR"."TBL_ESTADO_SEQ";
  DROP SEQUENCE "VENDEDOR"."TBL_INGREDIENTE_PRODUCTO_SEQ";
  DROP SEQUENCE "VENDEDOR"."TBL_INGREDIENTE_SEQ";
  DROP SEQUENCE "VENDEDOR"."TBL_PEDIDO_SEQ";
  DROP SEQUENCE "VENDEDOR"."TBL_PEDIDO_USUARIO_SEQ";
  DROP SEQUENCE "VENDEDOR"."TBL_PERMISO_SEQ";
  DROP SEQUENCE "VENDEDOR"."TBL_PERMISO_USUARIO_SEQ";
  DROP SEQUENCE "VENDEDOR"."TBL_PRODUCTO_SEQ";
  DROP SEQUENCE "VENDEDOR"."TBL_PRODUCTO_TIENDA_SEQ";
  DROP SEQUENCE "VENDEDOR"."TBL_ROL_SEQ";
  DROP SEQUENCE "VENDEDOR"."TBL_TERMINAL_SEQ";
  DROP SEQUENCE "VENDEDOR"."TBL_TIENDA_SEQ";
  DROP SEQUENCE "VENDEDOR"."TBL_USUARIO_SEQ";
--------------------------------------------------------
--  DDL for Sequence TBL_CATEGORIA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VENDEDOR"."TBL_CATEGORIA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_CLIENTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VENDEDOR"."TBL_CLIENTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_ESTADO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VENDEDOR"."TBL_ESTADO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_INGREDIENTE_PRODUCTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VENDEDOR"."TBL_INGREDIENTE_PRODUCTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_INGREDIENTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VENDEDOR"."TBL_INGREDIENTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_PEDIDO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VENDEDOR"."TBL_PEDIDO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_PEDIDO_USUARIO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VENDEDOR"."TBL_PEDIDO_USUARIO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_PERMISO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VENDEDOR"."TBL_PERMISO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_PERMISO_USUARIO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VENDEDOR"."TBL_PERMISO_USUARIO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_PRODUCTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VENDEDOR"."TBL_PRODUCTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_PRODUCTO_TIENDA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VENDEDOR"."TBL_PRODUCTO_TIENDA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_ROL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VENDEDOR"."TBL_ROL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_TERMINAL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VENDEDOR"."TBL_TERMINAL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_TIENDA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VENDEDOR"."TBL_TIENDA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TBL_USUARIO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "VENDEDOR"."TBL_USUARIO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table TBL_CATEGORIA
--------------------------------------------------------

  CREATE TABLE "VENDEDOR"."TBL_CATEGORIA" 
   (	"ID_CATEGORIA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_CLIENTE
--------------------------------------------------------

  CREATE TABLE "VENDEDOR"."TBL_CLIENTE" 
   (	"ID_CLIENTE" NUMBER(*,0), 
	"IDENTIFICACION" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"DIRECCION" VARCHAR2(20 BYTE), 
	"TELEFONO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_ESTADO
--------------------------------------------------------

  CREATE TABLE "VENDEDOR"."TBL_ESTADO" 
   (	"ID_ESTADO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_INGREDIENTE
--------------------------------------------------------

  CREATE TABLE "VENDEDOR"."TBL_INGREDIENTE" 
   (	"ID_INGREDIENTE" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(2030 BYTE), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "VENDEDOR"."TBL_PRODUCTO" 
   (	"ID_PRODUCTO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"DESCRIPCION" VARCHAR2(50 BYTE), 
	"VALOR" NUMBER, 
	"DISPONIBLES" NUMBER(*,0), 
	"ID_CATEGORIA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_INGREDIENTE_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "VENDEDOR"."TBL_INGREDIENTE_PRODUCTO" 
   (	"ID_INGREDIENTE_PRODUCTO" NUMBER(*,0), 
	"ID_INGREDIENTE" NUMBER(*,0), 
	"ID_PRODUCTO" NUMBER(*,0), 
	"GRAMOS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_PEDIDO
--------------------------------------------------------

  CREATE TABLE "VENDEDOR"."TBL_PEDIDO" 
   (	"ID_PEDIDO" NUMBER(*,0), 
	"ID_CLIENTE" NUMBER(*,0), 
	"ID_PRODUCTO" NUMBER(*,0), 
	"ID_ESTADO" NUMBER(*,0), 
	"CANTIDAD" NUMBER(*,0), 
	"VALOR_TOTAL" NUMBER, 
	"DOMICILIO" VARCHAR2(100 CHAR) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_TERMINAL
--------------------------------------------------------

  CREATE TABLE "VENDEDOR"."TBL_TERMINAL" 
   (	"ID_TERMINAL" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_USUARIO
--------------------------------------------------------

  CREATE TABLE "VENDEDOR"."TBL_USUARIO" 
   (	"ID_USUARIO" NUMBER(*,0), 
	"NOMBRE_USUARIO" VARCHAR2(50 BYTE), 
	"CONTRASENA" VARCHAR2(50 BYTE), 
	"NOMBRE" VARCHAR2(50 BYTE), 
	"ID_ROL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_PEDIDO_USUARIO
--------------------------------------------------------

  CREATE TABLE "VENDEDOR"."TBL_PEDIDO_USUARIO" 
   (	"ID_PEDIDO_USUARIO" NUMBER(*,0), 
	"ID_PEDIDO" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"ID_TERMINAL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_PERMISO
--------------------------------------------------------

  CREATE TABLE "VENDEDOR"."TBL_PERMISO" 
   (	"ID_PERMISO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_PERMISO_USUARIO
--------------------------------------------------------

  CREATE TABLE "VENDEDOR"."TBL_PERMISO_USUARIO" 
   (	"ID_PERMISO_USUARIO" NUMBER(*,0), 
	"ID_PERMISO" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"NOMBRE_USUARIO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_TIENDA
--------------------------------------------------------

  CREATE TABLE "VENDEDOR"."TBL_TIENDA" 
   (	"ID_TIENDA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_PRODUCTO_TIENDA
--------------------------------------------------------

  CREATE TABLE "VENDEDOR"."TBL_PRODUCTO_TIENDA" 
   (	"ID_PRODUCTO_TIENDA" NUMBER(*,0), 
	"ID_PRODUCTO" NUMBER(*,0), 
	"ID_TIENDA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TBL_ROL
--------------------------------------------------------

  CREATE TABLE "VENDEDOR"."TBL_ROL" 
   (	"ID_ROL" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"DESCRIPCION" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into VENDEDOR.TBL_CATEGORIA
Insert into VENDEDOR.TBL_CATEGORIA (ID_CATEGORIA,NOMBRE,DESCRIPCION) values (1,'Comidas Rápidas','Perros calientes, Hamburguesas, pizzas');
Insert into VENDEDOR.TBL_CATEGORIA (ID_CATEGORIA,NOMBRE,DESCRIPCION) values (2,'Comidas tradicionales','Sancocho, Consome, etc');
Insert into VENDEDOR.TBL_CATEGORIA (ID_CATEGORIA,NOMBRE,DESCRIPCION) values (3,'Bebidas','Gaseosas, Jugos');
REM INSERTING into VENDEDOR.TBL_CLIENTE
Insert into VENDEDOR.TBL_CLIENTE (ID_CLIENTE,IDENTIFICACION,EMAIL,NOMBRE,DIRECCION,TELEFONO) values (1,'25706942','algo@gmail.com','Maria','Timbio cauca','3176349898');
REM INSERTING into VENDEDOR.TBL_ESTADO
Insert into VENDEDOR.TBL_ESTADO (ID_ESTADO,NOMBRE,DESCRIPCION) values (3,'Devuelto','El pedido ha sido devuelto');
Insert into VENDEDOR.TBL_ESTADO (ID_ESTADO,NOMBRE,DESCRIPCION) values (1,'En cola','El pedido esta en cola de atencion');
Insert into VENDEDOR.TBL_ESTADO (ID_ESTADO,NOMBRE,DESCRIPCION) values (2,'En proceso','El pedido esta en proceso');
Insert into VENDEDOR.TBL_ESTADO (ID_ESTADO,NOMBRE,DESCRIPCION) values (4,'Entregado','El pedido ha sido entregado');
Insert into VENDEDOR.TBL_ESTADO (ID_ESTADO,NOMBRE,DESCRIPCION) values (5,'Cancelado','El pedido ha sido cancelado');
Insert into VENDEDOR.TBL_ESTADO (ID_ESTADO,NOMBRE,DESCRIPCION) values (6,'Despachado','El pedido ha sido despachado de la tienda');
REM INSERTING into VENDEDOR.TBL_INGREDIENTE
Insert into VENDEDOR.TBL_INGREDIENTE (ID_INGREDIENTE,NOMBRE,DESCRIPCION) values (1,'Cebolla','Cebolla en rodajas');
Insert into VENDEDOR.TBL_INGREDIENTE (ID_INGREDIENTE,NOMBRE,DESCRIPCION) values (2,'Arroz','Arroz normal en tasa');
Insert into VENDEDOR.TBL_INGREDIENTE (ID_INGREDIENTE,NOMBRE,DESCRIPCION) values (3,'Lechuga','Lechuga normal desmechada');
REM INSERTING into VENDEDOR.TBL_INGREDIENTE_PRODUCTO
Insert into VENDEDOR.TBL_INGREDIENTE_PRODUCTO (ID_INGREDIENTE_PRODUCTO,ID_INGREDIENTE,ID_PRODUCTO,GRAMOS) values (1,1,1,100);
REM INSERTING into VENDEDOR.TBL_PEDIDO
Insert into VENDEDOR.TBL_PEDIDO (ID_PEDIDO,ID_CLIENTE,ID_PRODUCTO,ID_ESTADO,CANTIDAD,VALOR_TOTAL,DOMICILIO) values (63,1,2,1,1,6000,'En restaurante');
REM INSERTING into VENDEDOR.TBL_PEDIDO_USUARIO
REM INSERTING into VENDEDOR.TBL_PERMISO
Insert into VENDEDOR.TBL_PERMISO (ID_PERMISO,NOMBRE,DESCRIPCION) values (5,'Administrador','Puege realizar todas las configuraciones');
Insert into VENDEDOR.TBL_PERMISO (ID_PERMISO,NOMBRE,DESCRIPCION) values (4,'Inventario','Puede realizar el cruce entre producto y tienda');
Insert into VENDEDOR.TBL_PERMISO (ID_PERMISO,NOMBRE,DESCRIPCION) values (1,'Productos','Puede gestionar los productos y sus ingredientes');
Insert into VENDEDOR.TBL_PERMISO (ID_PERMISO,NOMBRE,DESCRIPCION) values (2,'Pedidos','Puede gestionar los pedidos');
Insert into VENDEDOR.TBL_PERMISO (ID_PERMISO,NOMBRE,DESCRIPCION) values (3,'Usuarios','Puege gestionar los usuarios');
REM INSERTING into VENDEDOR.TBL_PERMISO_USUARIO
Insert into VENDEDOR.TBL_PERMISO_USUARIO (ID_PERMISO_USUARIO,ID_PERMISO,ID_USUARIO,NOMBRE_USUARIO) values (10,1,5,'admin');
REM INSERTING into VENDEDOR.TBL_PRODUCTO
Insert into VENDEDOR.TBL_PRODUCTO (ID_PRODUCTO,NOMBRE,DESCRIPCION,VALOR,DISPONIBLES,ID_CATEGORIA) values (1,'Hamburguesa','Hamburguesa sencilla',80000,1,1);
Insert into VENDEDOR.TBL_PRODUCTO (ID_PRODUCTO,NOMBRE,DESCRIPCION,VALOR,DISPONIBLES,ID_CATEGORIA) values (2,'Perro caliente','Perro caliente sencillo',6000,7,1);
REM INSERTING into VENDEDOR.TBL_PRODUCTO_TIENDA
REM INSERTING into VENDEDOR.TBL_ROL
Insert into VENDEDOR.TBL_ROL (ID_ROL,NOMBRE,DESCRIPCION) values (1,'Cajero','Persona que recibe el dinero de un pedido');
Insert into VENDEDOR.TBL_ROL (ID_ROL,NOMBRE,DESCRIPCION) values (2,'Cocinero','Persona que recibe el pedido');
Insert into VENDEDOR.TBL_ROL (ID_ROL,NOMBRE,DESCRIPCION) values (3,'Mesero','Entrega el pedido');
Insert into VENDEDOR.TBL_ROL (ID_ROL,NOMBRE,DESCRIPCION) values (4,'Despachador','Entrega el pedido a solicitudes externas');
Insert into VENDEDOR.TBL_ROL (ID_ROL,NOMBRE,DESCRIPCION) values (5,'Administrador','Administra los pedidos, productos y usuarios');
Insert into VENDEDOR.TBL_ROL (ID_ROL,NOMBRE,DESCRIPCION) values (6,'Configurador','Configura opciones generales');
REM INSERTING into VENDEDOR.TBL_TERMINAL
Insert into VENDEDOR.TBL_TERMINAL (ID_TERMINAL,NOMBRE,DESCRIPCION) values (4,'Devoluciones','Indica que el pedido está en devolución');
Insert into VENDEDOR.TBL_TERMINAL (ID_TERMINAL,NOMBRE,DESCRIPCION) values (1,'Caja','Indica que el pedido aún esta en facturacion');
Insert into VENDEDOR.TBL_TERMINAL (ID_TERMINAL,NOMBRE,DESCRIPCION) values (2,'Despacho','Indica que el pedido esta por despachar');
Insert into VENDEDOR.TBL_TERMINAL (ID_TERMINAL,NOMBRE,DESCRIPCION) values (3,'Cocina','Indica que el pedido esta en cocina');
REM INSERTING into VENDEDOR.TBL_TIENDA
Insert into VENDEDOR.TBL_TIENDA (ID_TIENDA,NOMBRE,DESCRIPCION) values (1,'Mi restaurante','Tienda donde venden comida de todo tipo');
REM INSERTING into VENDEDOR.TBL_USUARIO
Insert into VENDEDOR.TBL_USUARIO (ID_USUARIO,NOMBRE_USUARIO,CONTRASENA,NOMBRE,ID_ROL) values (4,'despachador','4297f44b13955235245b2497399d7a93','Usuario despachador',4);
Insert into VENDEDOR.TBL_USUARIO (ID_USUARIO,NOMBRE_USUARIO,CONTRASENA,NOMBRE,ID_ROL) values (3,'mesero','4297f44b13955235245b2497399d7a93','Usuario Mesero',3);
Insert into VENDEDOR.TBL_USUARIO (ID_USUARIO,NOMBRE_USUARIO,CONTRASENA,NOMBRE,ID_ROL) values (5,'cajero','4297f44b13955235245b2497399d7a93','Usuario Cajero',1);
Insert into VENDEDOR.TBL_USUARIO (ID_USUARIO,NOMBRE_USUARIO,CONTRASENA,NOMBRE,ID_ROL) values (6,'configurador','4297f44b13955235245b2497399d7a93','Usuario Configurador',6);
Insert into VENDEDOR.TBL_USUARIO (ID_USUARIO,NOMBRE_USUARIO,CONTRASENA,NOMBRE,ID_ROL) values (2,'cocinero','4297f44b13955235245b2497399d7a93','Usuaro cocinero',2);
Insert into VENDEDOR.TBL_USUARIO (ID_USUARIO,NOMBRE_USUARIO,CONTRASENA,NOMBRE,ID_ROL) values (1,'admin','4297f44b13955235245b2497399d7a93','Santiago admin',5);
--------------------------------------------------------
--  DDL for Index TBL_CATEGORIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDEDOR"."TBL_CATEGORIA_PK" ON "VENDEDOR"."TBL_CATEGORIA" ("ID_CATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDEDOR"."TBL_CLIENTE_PK" ON "VENDEDOR"."TBL_CLIENTE" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_CLIENTE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDEDOR"."TBL_CLIENTE_UK1" ON "VENDEDOR"."TBL_CLIENTE" ("IDENTIFICACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_ESTADO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDEDOR"."TBL_ESTADO_PK" ON "VENDEDOR"."TBL_ESTADO" ("ID_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_INGREDIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDEDOR"."TBL_INGREDIENTE_PK" ON "VENDEDOR"."TBL_INGREDIENTE" ("ID_INGREDIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_INGREDIENTE_PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDEDOR"."TBL_INGREDIENTE_PRODUCTO_PK" ON "VENDEDOR"."TBL_INGREDIENTE_PRODUCTO" ("ID_INGREDIENTE_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_PEDIDO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDEDOR"."TBL_PEDIDO_PK" ON "VENDEDOR"."TBL_PEDIDO" ("ID_PEDIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_PEDIDO_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDEDOR"."TBL_PEDIDO_USUARIO_PK" ON "VENDEDOR"."TBL_PEDIDO_USUARIO" ("ID_PEDIDO_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_PERMISO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDEDOR"."TBL_PERMISO_PK" ON "VENDEDOR"."TBL_PERMISO" ("ID_PERMISO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_PERMISO_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDEDOR"."TBL_PERMISO_USUARIO_PK" ON "VENDEDOR"."TBL_PERMISO_USUARIO" ("ID_PERMISO_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDEDOR"."TBL_PRODUCTO_PK" ON "VENDEDOR"."TBL_PRODUCTO" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_PRODUCTO_TIENDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDEDOR"."TBL_PRODUCTO_TIENDA_PK" ON "VENDEDOR"."TBL_PRODUCTO_TIENDA" ("ID_PRODUCTO_TIENDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_ROL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDEDOR"."TBL_ROL_PK" ON "VENDEDOR"."TBL_ROL" ("ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_TERMINAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDEDOR"."TBL_TERMINAL_PK" ON "VENDEDOR"."TBL_TERMINAL" ("ID_TERMINAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_TIENDA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDEDOR"."TBL_TIENDA_PK" ON "VENDEDOR"."TBL_TIENDA" ("ID_TIENDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_USUARIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDEDOR"."TBL_USUARIO_PK" ON "VENDEDOR"."TBL_USUARIO" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TBL_USUARIO_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "VENDEDOR"."TBL_USUARIO_UK1" ON "VENDEDOR"."TBL_USUARIO" ("NOMBRE_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TBL_CATEGORIA
--------------------------------------------------------

  ALTER TABLE "VENDEDOR"."TBL_CATEGORIA" ADD CONSTRAINT "TBL_CATEGORIA_PK" PRIMARY KEY ("ID_CATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_CATEGORIA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_CATEGORIA" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_CLIENTE
--------------------------------------------------------

  ALTER TABLE "VENDEDOR"."TBL_CLIENTE" ADD CONSTRAINT "TBL_CLIENTE_UK1" UNIQUE ("IDENTIFICACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_CLIENTE" ADD CONSTRAINT "TBL_CLIENTE_PK" PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_CLIENTE" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_CLIENTE" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_CLIENTE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_CLIENTE" MODIFY ("IDENTIFICACION" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_CLIENTE" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_ESTADO
--------------------------------------------------------

  ALTER TABLE "VENDEDOR"."TBL_ESTADO" ADD CONSTRAINT "TBL_ESTADO_PK" PRIMARY KEY ("ID_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_ESTADO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_ESTADO" MODIFY ("ID_ESTADO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_INGREDIENTE
--------------------------------------------------------

  ALTER TABLE "VENDEDOR"."TBL_INGREDIENTE" ADD CONSTRAINT "TBL_INGREDIENTE_PK" PRIMARY KEY ("ID_INGREDIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_INGREDIENTE" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_INGREDIENTE" MODIFY ("ID_INGREDIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_INGREDIENTE_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "VENDEDOR"."TBL_INGREDIENTE_PRODUCTO" ADD CONSTRAINT "TBL_INGREDIENTE_PRODUCTO_PK" PRIMARY KEY ("ID_INGREDIENTE_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_INGREDIENTE_PRODUCTO" MODIFY ("GRAMOS" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_INGREDIENTE_PRODUCTO" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_INGREDIENTE_PRODUCTO" MODIFY ("ID_INGREDIENTE" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_INGREDIENTE_PRODUCTO" MODIFY ("ID_INGREDIENTE_PRODUCTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_PEDIDO
--------------------------------------------------------

  ALTER TABLE "VENDEDOR"."TBL_PEDIDO" ADD CONSTRAINT "TBL_PEDIDO_PK" PRIMARY KEY ("ID_PEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_PEDIDO" MODIFY ("VALOR_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_PEDIDO" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_PEDIDO" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_PEDIDO" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_PEDIDO" MODIFY ("ID_PEDIDO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_PEDIDO_USUARIO
--------------------------------------------------------

  ALTER TABLE "VENDEDOR"."TBL_PEDIDO_USUARIO" ADD CONSTRAINT "TBL_PEDIDO_USUARIO_PK" PRIMARY KEY ("ID_PEDIDO_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_PEDIDO_USUARIO" MODIFY ("ID_TERMINAL" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_PEDIDO_USUARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_PEDIDO_USUARIO" MODIFY ("ID_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_PEDIDO_USUARIO" MODIFY ("ID_PEDIDO_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_PERMISO
--------------------------------------------------------

  ALTER TABLE "VENDEDOR"."TBL_PERMISO" ADD CONSTRAINT "TBL_PERMISO_PK" PRIMARY KEY ("ID_PERMISO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_PERMISO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_PERMISO" MODIFY ("ID_PERMISO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_PERMISO_USUARIO
--------------------------------------------------------

  ALTER TABLE "VENDEDOR"."TBL_PERMISO_USUARIO" MODIFY ("NOMBRE_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_PERMISO_USUARIO" ADD CONSTRAINT "TBL_PERMISO_USUARIO_PK" PRIMARY KEY ("ID_PERMISO_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_PERMISO_USUARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_PERMISO_USUARIO" MODIFY ("ID_PERMISO_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "VENDEDOR"."TBL_PRODUCTO" ADD CONSTRAINT "TBL_PRODUCTO_PK" PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_PRODUCTO" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_PRODUCTO" MODIFY ("DISPONIBLES" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_PRODUCTO" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_PRODUCTO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_PRODUCTO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_PRODUCTO" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_PRODUCTO_TIENDA
--------------------------------------------------------

  ALTER TABLE "VENDEDOR"."TBL_PRODUCTO_TIENDA" ADD CONSTRAINT "TBL_PRODUCTO_TIENDA_PK" PRIMARY KEY ("ID_PRODUCTO_TIENDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_PRODUCTO_TIENDA" MODIFY ("ID_TIENDA" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_PRODUCTO_TIENDA" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_PRODUCTO_TIENDA" MODIFY ("ID_PRODUCTO_TIENDA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_ROL
--------------------------------------------------------

  ALTER TABLE "VENDEDOR"."TBL_ROL" ADD CONSTRAINT "TBL_ROL_PK" PRIMARY KEY ("ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_ROL" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_ROL" MODIFY ("ID_ROL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TERMINAL
--------------------------------------------------------

  ALTER TABLE "VENDEDOR"."TBL_TERMINAL" ADD CONSTRAINT "TBL_TERMINAL_PK" PRIMARY KEY ("ID_TERMINAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_TERMINAL" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_TERMINAL" MODIFY ("ID_TERMINAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_TIENDA
--------------------------------------------------------

  ALTER TABLE "VENDEDOR"."TBL_TIENDA" ADD CONSTRAINT "TBL_TIENDA_PK" PRIMARY KEY ("ID_TIENDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_TIENDA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_TIENDA" MODIFY ("ID_TIENDA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TBL_USUARIO
--------------------------------------------------------

  ALTER TABLE "VENDEDOR"."TBL_USUARIO" ADD CONSTRAINT "TBL_USUARIO_UK1" UNIQUE ("NOMBRE_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_USUARIO" ADD CONSTRAINT "TBL_USUARIO_PK" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_USUARIO" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_USUARIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_USUARIO" MODIFY ("CONTRASENA" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_USUARIO" MODIFY ("NOMBRE_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "VENDEDOR"."TBL_USUARIO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TBL_INGREDIENTE_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "VENDEDOR"."TBL_INGREDIENTE_PRODUCTO" ADD CONSTRAINT "TBL_INGREDIENTE_PRODUCTO__FKI" FOREIGN KEY ("ID_INGREDIENTE")
	  REFERENCES "VENDEDOR"."TBL_INGREDIENTE" ("ID_INGREDIENTE") ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_INGREDIENTE_PRODUCTO" ADD CONSTRAINT "TBL_INGREDIENTE_PRODUCTO__FKP" FOREIGN KEY ("ID_PRODUCTO")
	  REFERENCES "VENDEDOR"."TBL_PRODUCTO" ("ID_PRODUCTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_PEDIDO
--------------------------------------------------------

  ALTER TABLE "VENDEDOR"."TBL_PEDIDO" ADD CONSTRAINT "TBL_PEDIDO_TBL_CLIENTE_FK1" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "VENDEDOR"."TBL_CLIENTE" ("ID_CLIENTE") ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_PEDIDO" ADD CONSTRAINT "TBL_PEDIDO_TBL_ESTADO_FK1" FOREIGN KEY ("ID_ESTADO")
	  REFERENCES "VENDEDOR"."TBL_ESTADO" ("ID_ESTADO") ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_PEDIDO" ADD CONSTRAINT "TBL_PEDIDO_TBL_PRODUCTO_FK1" FOREIGN KEY ("ID_PRODUCTO")
	  REFERENCES "VENDEDOR"."TBL_PRODUCTO" ("ID_PRODUCTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_PEDIDO_USUARIO
--------------------------------------------------------

  ALTER TABLE "VENDEDOR"."TBL_PEDIDO_USUARIO" ADD CONSTRAINT "TBL_PEDIDO_USUARIO_TBL_PE_FK1" FOREIGN KEY ("ID_PEDIDO")
	  REFERENCES "VENDEDOR"."TBL_PEDIDO" ("ID_PEDIDO") ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_PEDIDO_USUARIO" ADD CONSTRAINT "TBL_PEDIDO_USUARIO_TBL_TE_FK1" FOREIGN KEY ("ID_TERMINAL")
	  REFERENCES "VENDEDOR"."TBL_TERMINAL" ("ID_TERMINAL") ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_PEDIDO_USUARIO" ADD CONSTRAINT "TBL_PEDIDO_USUARIO_TBL_US_FK1" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "VENDEDOR"."TBL_USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_PERMISO_USUARIO
--------------------------------------------------------

  ALTER TABLE "VENDEDOR"."TBL_PERMISO_USUARIO" ADD CONSTRAINT "TBL_PERMISO_USUARIO_TBL_P_FK1" FOREIGN KEY ("ID_PERMISO")
	  REFERENCES "VENDEDOR"."TBL_PERMISO" ("ID_PERMISO") ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_PERMISO_USUARIO" ADD CONSTRAINT "TBL_PERMISO_USUARIO_TBL_U_FK1" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "VENDEDOR"."TBL_USUARIO" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "VENDEDOR"."TBL_PRODUCTO" ADD CONSTRAINT "TBL_PRODUCTO_TBL_CATEGORI_FK1" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "VENDEDOR"."TBL_CATEGORIA" ("ID_CATEGORIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_PRODUCTO_TIENDA
--------------------------------------------------------

  ALTER TABLE "VENDEDOR"."TBL_PRODUCTO_TIENDA" ADD CONSTRAINT "TBL_PRODUCTO_TIENDA_FKP" FOREIGN KEY ("ID_PRODUCTO")
	  REFERENCES "VENDEDOR"."TBL_PRODUCTO" ("ID_PRODUCTO") ENABLE;
  ALTER TABLE "VENDEDOR"."TBL_PRODUCTO_TIENDA" ADD CONSTRAINT "TBL_PRODUCTO_TIENDA_FKT" FOREIGN KEY ("ID_TIENDA")
	  REFERENCES "VENDEDOR"."TBL_TIENDA" ("ID_TIENDA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TBL_USUARIO
--------------------------------------------------------

  ALTER TABLE "VENDEDOR"."TBL_USUARIO" ADD CONSTRAINT "TBL_USUARIO_TBL_ROL_FK1" FOREIGN KEY ("ID_ROL")
	  REFERENCES "VENDEDOR"."TBL_ROL" ("ID_ROL") ENABLE;
--------------------------------------------------------
--  DDL for Synonymn DUAL
--------------------------------------------------------

  CREATE OR REPLACE PUBLIC SYNONYM "DUAL" FOR "SYS"."DUAL";
--------------------------------------------------------
--  DDL for Trigger TBL_CATEGORIA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VENDEDOR"."TBL_CATEGORIA_TRG" BEFORE INSERT ON TBL_CATEGORIA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_CATEGORIA IS NULL THEN
      SELECT TBL_CATEGORIA_SEQ.NEXTVAL INTO :NEW.ID_CATEGORIA FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VENDEDOR"."TBL_CATEGORIA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_CLIENTE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VENDEDOR"."TBL_CLIENTE_TRG" BEFORE INSERT ON TBL_CLIENTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_CLIENTE IS NULL THEN
      SELECT TBL_CLIENTE_SEQ.NEXTVAL INTO :NEW.ID_CLIENTE FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VENDEDOR"."TBL_CLIENTE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_ESTADO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VENDEDOR"."TBL_ESTADO_TRG" BEFORE INSERT ON TBL_ESTADO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_ESTADO IS NULL THEN
      SELECT TBL_ESTADO_SEQ.NEXTVAL INTO :NEW.ID_ESTADO FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VENDEDOR"."TBL_ESTADO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_INGREDIENTE_PRODUCTO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VENDEDOR"."TBL_INGREDIENTE_PRODUCTO_TRG" BEFORE INSERT ON TBL_INGREDIENTE_PRODUCTO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_INGREDIENTE_PRODUCTO IS NULL THEN
      SELECT TBL_INGREDIENTE_PRODUCTO_SEQ.NEXTVAL INTO :NEW.ID_INGREDIENTE_PRODUCTO FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VENDEDOR"."TBL_INGREDIENTE_PRODUCTO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_INGREDIENTE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VENDEDOR"."TBL_INGREDIENTE_TRG" BEFORE INSERT ON TBL_INGREDIENTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_INGREDIENTE IS NULL THEN
      SELECT TBL_INGREDIENTE_SEQ.NEXTVAL INTO :NEW.ID_INGREDIENTE FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VENDEDOR"."TBL_INGREDIENTE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_PEDIDO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VENDEDOR"."TBL_PEDIDO_TRG" BEFORE INSERT ON TBL_PEDIDO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_PEDIDO IS NULL THEN
      SELECT TBL_PEDIDO_SEQ.NEXTVAL INTO :NEW.ID_PEDIDO FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VENDEDOR"."TBL_PEDIDO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_PEDIDO_USUARIO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VENDEDOR"."TBL_PEDIDO_USUARIO_TRG" BEFORE INSERT ON TBL_PEDIDO_USUARIO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_PEDIDO_USUARIO IS NULL THEN
      SELECT TBL_PEDIDO_USUARIO_SEQ.NEXTVAL INTO :NEW.ID_PEDIDO_USUARIO FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VENDEDOR"."TBL_PEDIDO_USUARIO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_PERMISO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VENDEDOR"."TBL_PERMISO_TRG" BEFORE INSERT ON TBL_PERMISO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_PERMISO IS NULL THEN
      SELECT TBL_PERMISO_SEQ.NEXTVAL INTO :NEW.ID_PERMISO FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VENDEDOR"."TBL_PERMISO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_PERMISO_USUARIO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VENDEDOR"."TBL_PERMISO_USUARIO_TRG" BEFORE INSERT ON TBL_PERMISO_USUARIO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_PERMISO_USUARIO IS NULL THEN
      SELECT TBL_PERMISO_USUARIO_SEQ.NEXTVAL INTO :NEW.ID_PERMISO_USUARIO FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VENDEDOR"."TBL_PERMISO_USUARIO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_PRODUCTO_TIENDA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VENDEDOR"."TBL_PRODUCTO_TIENDA_TRG" BEFORE INSERT ON TBL_PRODUCTO_TIENDA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_PRODUCTO_TIENDA IS NULL THEN
      SELECT TBL_PRODUCTO_TIENDA_SEQ.NEXTVAL INTO :NEW.ID_PRODUCTO_TIENDA FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VENDEDOR"."TBL_PRODUCTO_TIENDA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_PRODUCTO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VENDEDOR"."TBL_PRODUCTO_TRG" BEFORE INSERT ON TBL_PRODUCTO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_PRODUCTO IS NULL THEN
      SELECT TBL_PRODUCTO_SEQ.NEXTVAL INTO :NEW.ID_PRODUCTO FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VENDEDOR"."TBL_PRODUCTO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_ROL_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VENDEDOR"."TBL_ROL_TRG" BEFORE INSERT ON TBL_ROL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_ROL IS NULL THEN
      SELECT TBL_ROL_SEQ.NEXTVAL INTO :NEW.ID_ROL FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VENDEDOR"."TBL_ROL_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_TERMINAL_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VENDEDOR"."TBL_TERMINAL_TRG" BEFORE INSERT ON TBL_TERMINAL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_TERMINAL IS NULL THEN
      SELECT TBL_TERMINAL_SEQ.NEXTVAL INTO :NEW.ID_TERMINAL FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VENDEDOR"."TBL_TERMINAL_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_TIENDA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VENDEDOR"."TBL_TIENDA_TRG" BEFORE INSERT ON TBL_TIENDA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_TIENDA IS NULL THEN
      SELECT TBL_TIENDA_SEQ.NEXTVAL INTO :NEW.ID_TIENDA FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VENDEDOR"."TBL_TIENDA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TBL_USUARIO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "VENDEDOR"."TBL_USUARIO_TRG" BEFORE INSERT ON TBL_USUARIO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF :NEW.ID_USUARIO IS NULL THEN
      SELECT TBL_USUARIO_SEQ.NEXTVAL INTO :NEW.ID_USUARIO FROM DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "VENDEDOR"."TBL_USUARIO_TRG" ENABLE;
